### ISSUE TITLE
request the paper of MT-GBDT

### ISSUE THREAD

**Issue by mmgongnpu** [felixwzh/MT-GBDT#1]
Hi, could you please send the paper of MT-GBDT to me?

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:

Compiler:

Package used (python/R/jvm/C++):

`xgboost` version used:

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution

If you are using python package, please provide

1. The python version and distribution
2. The command to install `xgboost` if you are not installing from source

If you are using R package, please provide

1. The R `sessionInfo()`
2. The command to install `xgboost` if you are not installing from source

## Steps to reproduce

1.
2.
3.

## What have you tried?

1.
2.
3.

**Comment by felixwzh** [comment]
maybe you can send me an email?

**Comment by mmgongnpu** [comment]
> maybe you can send me an email?

Yeah, thanks so much. Here is my email address, mmgong@foxmail.com.
Best wishes

**Comment by qiuwei** [comment]
@felixwzh Any chance that you can share the paper with me (wei@qiu.es). Many thanks!

**Comment by felixwzh** [comment]
please find the paper here: [Task-wise Split Gradient Boosting Trees for Multi-center Diabetes Prediction](https://arxiv.org/abs/2108.07107)
