### ISSUE TITLE
30 Task limit

### ISSUE THREAD

**Issue by uziahmd** [felixwzh/MT-GBDT#2]
I want to try the code on a relatively big number of tasks (45) but there is a default limit set to 30 and it keeps giving me the following error.

"terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 30) >= this->size() (which is 30)
Aborted (core dumped)"

How can I modify the code to allow such a amplification.

**Comment by felixwzh** [comment]
here are some possible solutions:
1. add some params here:
https://github.com/felixwzh/MT-GBDT/blob/ee018470c4e1f8ed224a1dfd80d41daa89c9e3aa/demo/multi_task_binary_classification/basic_walkthrough.py#L35

```
"task_num_for_init_vec": 45,
"num_task": 45,
```

2. if the params above doesn't work, change the `int task_num_for_init_vec = 45` here, and re-build the project. I guess I somehow hardcoded it here.
https://github.com/felixwzh/MT-GBDT/blob/ee018470c4e1f8ed224a1dfd80d41daa89c9e3aa/src/tree/updater_colmaker.cc#L2928

please let me know if you hare any question

**Comment by uziahmd** [comment]
Hello,

Thank you for your reply. Re-building the repository with the edit worked. 
I had another question which is that is the new split mechanism that you added been implemented for a specific tree method i.e. exact or does it also work for all the tree methods (like hist).

Thank you.

**Comment by felixwzh** [comment]
great. 
I think it only works for the exact split.
