### ISSUE TITLE
Can i use this branch to testrun training

### ISSUE THREAD

**Issue by aniruddhghatpande** [felixwzh/MT-GBDT#3]
Hi @felixwzh ,

I was looking to use a feature to run multi task GBDT. I came across this code base and the paper  https://arxiv.org/abs/2201.06239. 

Is this branch functional and can i use it for training. Also would you have a code snippet to specify multi task for config?

**Comment by felixwzh** [comment]
you can check these two links, they should have similar things. 
https://github.com/felixwzh/MT-GBDT/tree/master/demo/multi_task_binary_classification
https://github.com/felixwzh/TSGB/tree/main/demo/multi_task_binary_classification
